[package]
name = "stacker-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.9"
quote = "1.0.36"
stacker = "0.1"
syn = { version = "2.0.66", features = ["full"] }
